version: 0.2
phases:
  pre_build:
    commands:
      - cat /etc/os-release
      - echo Logging in to Amazon ECR...
      - echo aws cli is installed
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 383882307471.dkr.ecr.ap-south-1.amazonaws.com
      - echo authentication is completed..........
      - REPOSITORY_URI=383882307471.dkr.ecr.ap-south-1.amazonaws.com/django-build-img
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker images
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"django","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json